### ISSUE TITLE
Package won't work with Laravel Vapor deployments

### ISSUE THREAD

**Issue by brianrlewis** [magiclabs/magic-laravel#1]
@FYJen 

I recently discovered that [magic-admin-php](https://github.com/magiclabs/magic-admin-php) won't work with my project in production because my production environment uses Laravel Vapor, which is a serverless platform that uses a custom AWS Lambda runtime. The reason for this is that the php-gmp extension is not installed on that custom runtime.

However it should be possible for magic-admin-php to function without php-gmp installed as long as php-bcmath is installed. I know this because my unofficial version ([php-magic-admin](https://github.com/brianrlewis/php-magic-admin)) is able to function fine within Laravel Vapor.

Both [magic-admin-php](https://github.com/magiclabs/magic-admin-php) and [php-magic-admin](https://github.com/brianrlewis/php-magic-admin) use the same dependency `simplito/elliptic-php` but the official package uses it indirectly through `digitaldonkey/ecverify`. The way `digitaldonkey/ecverify` calls `$ec->recoverPubKey($message_hash, $sign, $recid)` is a little different then the way my unofficial package calls that same function.

That slight difference causes an error when the runtime does not have gmp installed but does have bcmath installed. That is because `simplito/elliptic-php` is designed to work with either the gmp or bcmath extension.

I submitted an [issue](https://github.com/digitaldonkey/ecverify/issues/2) to the [digitaldonkey/ecverify](https://github.com/digitaldonkey/ecverify) repo in hopes of rectifying this issue. Please read that issue for more details about the specific problem.

Before magic-laravel is released it would be great to see if there is some workaround we can implement to accommodate Laravel Vapor users since it is definitely possible to have [magic-admin-php](https://github.com/magiclabs/magic-admin-php) work without gmp installed as long as the runtime has bcmath. If we can't come up with a workaround then we should put a clear warning in the readme to let users know that this package will not work on Vapor.

I asked the Laravel Vapor team about whether or not the gmp extension could be installed somehow. They said they are working on a way for users to be able to customize the runtime but that capability is not yet available. There are some articles describing how to customize the Vapor runtime yourself but the instructions looked fairly involved and I haven't had a chance to take a crack at it yet.

**Comment by FYJen** [comment]
An other quick update on this. https://github.com/magiclabs/magic-laravel/pull/3 addresses this issue. Closing.
